#!/bin/bash
# =============================================================================
# Gather Config -- Interactively collects environment values for the agent
# =============================================================================
# Run this after env-check.sh passes. It prompts for each integration
# endpoint and generates the configuration files needed for deployment.
#
# Usage: ./scripts/gather-config.sh
# Output: config/agent.env, config/secrets.sh
# =============================================================================

set -euo pipefail

GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

mkdir -p config

echo ""
echo "=============================================="
echo "  Migration Agent -- Configuration Wizard"
echo "=============================================="
echo ""
echo "This will collect your environment values and generate"
echo "the configuration needed to deploy the agent."
echo "Press Enter to accept defaults shown in [brackets]."
echo ""

# --- Deployment namespace ---
read -rp "OpenShift namespace for the agent [adk-web]: " NAMESPACE
NAMESPACE=${NAMESPACE:-adk-web}

# --- LLM ---
echo ""
echo -e "${BLUE}-- LLM Configuration --${NC}"
read -rp "LLM API base URL (e.g., https://vllm-svc.ns.svc:8080/v1): " LLM_BASE
read -rp "LLM API key [not-needed]: " LLM_KEY
LLM_KEY=${LLM_KEY:-not-needed}
read -rp "Model name [openai/gpt-oss-120b]: " MODEL_NAME
MODEL_NAME=${MODEL_NAME:-openai/gpt-oss-120b}

# --- MTV ---
echo ""
echo -e "${BLUE}-- MTV Cluster (VMware migration) --${NC}"
echo "Leave empty if MTV is on the same cluster or not yet configured."
read -rp "MTV cluster API URL: " MTV_URL
MTV_TOKEN=""
if [ -n "$MTV_URL" ]; then
    read -rp "MTV cluster bearer token: " MTV_TOKEN
fi

# --- OCP Virt ---
echo ""
echo -e "${BLUE}-- OCP Virt Cluster --${NC}"
echo "Leave empty if same as MTV cluster."
read -rp "OCP Virt cluster API URL: " VIRT_URL
VIRT_TOKEN=""
if [ -n "$VIRT_URL" ]; then
    read -rp "OCP Virt cluster bearer token: " VIRT_TOKEN
fi

# --- AAP ---
echo ""
echo -e "${BLUE}-- AAP Controller (Ansible Automation Platform) --${NC}"
echo "Leave empty if AAP is not yet configured."
read -rp "AAP Controller URL: " AAP_URL_VAL
AAP_TOKEN_VAL=""
if [ -n "$AAP_URL_VAL" ]; then
    read -rp "AAP bearer token: " AAP_TOKEN_VAL
fi

# --- Namespaces ---
echo ""
echo -e "${BLUE}-- Namespace Defaults --${NC}"
read -rp "MTV provider namespace [mtv-user1]: " MTV_NS
MTV_NS=${MTV_NS:-mtv-user1}
read -rp "Migrated VM namespace [vmimported-user1]: " VIRT_NS
VIRT_NS=${VIRT_NS:-vmimported-user1}

# --- Generate agent.env ---
cat > config/agent.env << ENVEOF
# Generated by gather-config.sh on $(date)
OPENAI_API_BASE=$LLM_BASE
OPENAI_API_KEY=$LLM_KEY
ADK_MODEL=$MODEL_NAME
AGENT_NAME=migration_agent
AGENT_MODE=single
ADK_TEMPERATURE=0.2
ADK_MAX_OUTPUT_TOKENS=4096
MTV_API_URL=$MTV_URL
VIRT_API_URL=$VIRT_URL
AAP_URL=$AAP_URL_VAL
DEFAULT_MTV_NAMESPACE=$MTV_NS
DEFAULT_VIRT_NAMESPACE=$VIRT_NS
MTV_OPERATOR_NAMESPACE=openshift-mtv
ENVEOF

echo ""
echo -e "${GREEN}Generated: config/agent.env${NC}"

# --- Generate secrets script ---
cat > config/secrets.sh << SECEOF
#!/bin/bash
# Generated by gather-config.sh -- creates Kubernetes Secrets
# Run: bash config/secrets.sh -n $NAMESPACE

NAMESPACE=\${1:-$NAMESPACE}

SECEOF

if [ -n "$MTV_TOKEN" ]; then
    cat >> config/secrets.sh << SECEOF
oc create secret generic mtv-cluster-token \\
  --from-literal=token='$MTV_TOKEN' \\
  -n \$NAMESPACE --dry-run=client -o yaml | oc apply -f -

SECEOF
fi

if [ -n "$VIRT_TOKEN" ]; then
    cat >> config/secrets.sh << SECEOF
oc create secret generic virt-cluster-token \\
  --from-literal=token='$VIRT_TOKEN' \\
  -n \$NAMESPACE --dry-run=client -o yaml | oc apply -f -

SECEOF
fi

if [ -n "$AAP_TOKEN_VAL" ]; then
    cat >> config/secrets.sh << SECEOF
oc create secret generic aap-agent-token \\
  --from-literal=token='$AAP_TOKEN_VAL' \\
  -n \$NAMESPACE --dry-run=client -o yaml | oc apply -f -

SECEOF
fi

echo "echo 'Secrets created in namespace \$NAMESPACE'" >> config/secrets.sh
chmod +x config/secrets.sh

echo -e "${GREEN}Generated: config/secrets.sh${NC}"

# --- Summary ---
echo ""
echo "=============================================="
echo "  Configuration Complete"
echo "=============================================="
echo ""
echo "  Namespace:  $NAMESPACE"
echo "  LLM:        $LLM_BASE ($MODEL_NAME)"
echo "  MTV:        ${MTV_URL:-not configured}"
echo "  OCP Virt:   ${VIRT_URL:-same as MTV}"
echo "  AAP:        ${AAP_URL_VAL:-not configured}"
echo ""
echo "Next steps:"
echo "  1. Review config/agent.env"
echo "  2. Run: bash config/secrets.sh -n $NAMESPACE"
echo "  3. Run: ./scripts/deploy-phase0.sh $NAMESPACE"
echo ""
